// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgdfhbebllcuhvnfyftn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnZGZoYmVibGxjdWh2bmZ5ZnRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTAwMDYsImV4cCI6MjA3NDcyNjAwNn0.OKjYRRejLA7HgVdeF5C_UuM57er382t5X-bSFxyQwF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});